### PR TITLE
Eguns now have electrodes instead of disablers

### PR DESCRIPTION
**Pull request by Spacedong**
Self explanatory.

### CODE REVIEW

**Comment by BTFO** [comment]
what about tazers

**Comment by Spacedong** [comment]
tasers always had electrodes and disabler mode didn't they?

**Comment by BTFO** [comment]
yeah but its shit

**Comment by JohnGinnane** [comment]
What do the icons look like? Does it show yellow for stun and red for kill?

**Comment by yobob591** [comment]
Nah I like this, it discourages the meme stun insta death by forcing you to carry a taser along with a lethal wepon

**Comment by Spacedong** [comment]
@JohnGinnane would still be blue for electrodes, do you want them yellow?

**Comment by JohnGinnane** [comment]
I think so, for consistency, like hos gun:

Red - lasers
Yellow - stun
Blue - disabler

**Comment by Spacedong** [comment]
if someone can provide the sprites i'll add them

**Comment by JamieH** [comment]
Check the old code

**Comment by Spacedong** [comment]
tfw

**Pull request closed without merging**
