### PR TITLE
E-guns now shoot electrodes instead of disablers

### PR DESCRIPTION
**Pull request by Spacedong**
Updated the sprites as well. Tested in-game and it works fine.

### CODE REVIEW

**Comment by JamieH** [comment]
You don't need to remove the disable state from the guns.dm, put that back incase we ever use it.

**Comment by Spacedong** [comment]
we'll never use it

**Comment by JamieH** [comment]
I don't care, there is no need to remove it, put it back.

**Comment by Spacedong** [comment]
if I don't remove it, it'll stay blue

**Comment by JamieH** [comment]
Okay - let me give you the proper solution to this then.

**Comment by MethMedic** [comment]
Blue>yellow also disablers are way better

**Comment by cacogen** [comment]
electrodes are better because you only have to hit them once to stun them

**Pull request closed without merging**
