### PR TITLE
Fixed cryo not instantly rejecting, among other improvements to it

### PR DESCRIPTION
**Pull request by Spacedong**
- Cryo no longer takes time to eject, instead it ejects you instantly upon reaching 100 health or if you resist.
- Cryo no longer puts you into an unconscious state of hell from which there is no escape.

NOTE: You still need someone to put you into cryo. I didn't change this because in my opinion it will allow medical doctors to actually do their job. If someone wants this changed I'll do it.

### CODE REVIEW

**Comment by Spacedong** [comment]
suck my dick travis

**Comment by JohnGinnane** [comment]
Thanks Spacedong :~)

**Comment by Spacedong** [comment]
>bad feature

??????????????????

**Comment by JohnGinnane** [comment]
As in it's a bad feature you're removing but i can see it being misleading, sorry

**Comment by McBawbaggings** [comment]
Yeah sure, artificial delays like this are cancerous anyway.

**Comment by JamieH** [comment]
`code/modules/atmospherics/machinery/components/unary_devices/cryo.dm:112:warning: T: variable defined but not used
`

**Comment by JamieH** [comment]
https://github.com/Spacedong/HippieStation13-rebase/blob/fb87a1ecfcbfeaf7ec75d0cd3d1a8270ff4a3c65/code/modules/atmospherics/machinery/components/unary_devices/cryo.dm#L112

**Comment by Spacedong** [comment]
that was there when i got there

**Comment by Spacedong** [comment]
anyways it doesn't matter

**Comment by JamieH** [comment]
Remove the line - you're no longer using it's throwing a warning.

**Pull request closed without merging**
