### PR TITLE
Empsound

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: EMP sound update
add: Electromagnetic pulses make noise.
/:cl:

### CODE REVIEW

**Comment by PopNotes** [comment]
[In-Game Preview.](http://puu.sh/tU6HW/f33f7ccddd.mp4)

**Comment by Spacedong** [comment]
that sounds really neat

**Comment by McBawbaggings** [comment]
+1 good sfx 🥇

**Comment by Dudeinyourbackyard** [comment]
nice go ahead +1

**Comment by JamieH** [comment]
fucking cool.

**Pull request merged**
